[workspace]
resolver = "2"
members = [
    "harness",
    "hub",
    "lib",
    "miner",
    "node",
    "sdk",
    "wallet",
]


[workspace.dependencies]
ciborium = "0.2.2"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.198", features = ["derive"] }
sha256 = "1.5.0"
uint = "0.9.5"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
k256 = { version = "0.13.3", features = ["serde", "pem"] }
ecdsa = { version = "0.16.9", features = ["signing", "verifying", 
"serde", "pem"] }
hex = "0.4.3"
rand = "0.8"
thiserror = "1.0.59"
bigdecimal = "0.4.5"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
