"""Cross-language conformance for the *other* signature an agent makes:
a spend of one of its own outputs into a particular set of payments,
which is what each input of ``POST /wallet/send`` carries. Verified
against ``tests/fixtures/output_fixtures.json``, generated by the same
Rust program as the envelope fixtures (``sdk/examples/gen_fixtures.rs``)
from ``Transaction::spend_commitment`` -- the exact code the hub and the
node verify against.

The preimage is hand-built on both sides (no CBOR outside Rust), so the
fixtures pin the bytes as well as the signature over them: a failure in
``test_the_commitment_bytes_match`` and not in the signature test means
the layout drifted, which is the more likely of the two.

Regenerate the fixture file with: cargo run -p sdk --example gen_fixtures
"""

import hashlib
import json
from pathlib import Path

import pytest

from itx_agent_sdk.envelope import Agent, spend_commitment_preimage

FIXTURES_PATH = Path(__file__).parent / "fixtures" / "output_fixtures.json"

with open(FIXTURES_PATH, encoding="utf-8") as f:
    FIXTURES = json.load(f)


def test_fixture_file_is_present_and_non_empty():
    assert len(FIXTURES) >= 3


@pytest.mark.parametrize("fixture", FIXTURES, ids=[f["name"] for f in FIXTURES])
def test_the_commitment_bytes_match(fixture):
    """The preimage's own hash, before any signing: `Hash::hash_bytes` of
    `Transaction::spend_commitment`'s layout. Checked separately so a
    drift in the bytes cannot be mistaken for a drift in the ECDSA."""
    preimage = spend_commitment_preimage(fixture["hash"], fixture["pays"])
    assert hashlib.sha256(preimage).hexdigest() == fixture["expected_commitment_hex"]


@pytest.mark.parametrize("fixture", FIXTURES, ids=[f["name"] for f in FIXTURES])
def test_signing_a_spend_matches_the_chain_byte_for_byte(fixture):
    """The hash arrives exactly as the hub reports it (`hex::encode` of
    `Hash::as_bytes`), the outputs exactly as `POST /wallet/send` sends
    them, and the signature has to be the one the chain verifies:
    RFC6979, low-S, `r || s`."""
    agent = Agent.from_private_key_hex(fixture["private_key_hex"])
    assert agent.pubkey_hex == fixture["pubkey_hex"]
    assert agent.sign_spend(fixture["hash"], fixture["pays"]) == fixture["expected_signature_hex"]


@pytest.mark.parametrize("fixture", FIXTURES, ids=[f["name"] for f in FIXTURES])
def test_the_payment_is_what_is_signed(fixture):
    """The property the whole commitment exists for: change who is paid,
    or how much, or in what order, and the signature no longer stands. A
    client that signed only the output hash would pass every other test
    here and hand the hub a blank cheque."""
    agent = Agent.from_private_key_hex(fixture["private_key_hex"])
    signed = fixture["expected_signature_hex"]

    elsewhere = [dict(o) for o in fixture["pays"]]
    elsewhere[0]["pubkey"] = "02" + "11" * 32
    assert agent.sign_spend(fixture["hash"], elsewhere) != signed

    more = [dict(o) for o in fixture["pays"]]
    more[0]["value"] = int(more[0]["value"]) + 1
    assert agent.sign_spend(fixture["hash"], more) != signed

    if len(fixture["pays"]) > 1:
        reordered = list(reversed([dict(o) for o in fixture["pays"]]))
        assert agent.sign_spend(fixture["hash"], reordered) != signed


def test_the_same_spend_signed_by_two_keys_is_two_signatures():
    by_name = {f["name"]: f for f in FIXTURES}
    a, b = by_name["faucet_grant_sized_spend"], by_name["small_spend_other_key"]
    assert a["expected_signature_hex"] != b["expected_signature_hex"]


def test_a_spend_signature_is_not_an_envelope_signature():
    """Two SHA-256 rounds over bytes, not over a JSON signing string: an
    implementation that reused `sign_message` on the hex would produce
    something that verifies nowhere."""
    fixture = FIXTURES[0]
    agent = Agent.from_private_key_hex(fixture["private_key_hex"])
    assert agent.sign_message(fixture["hash"]) != fixture["expected_signature_hex"]


def test_a_malformed_spend_is_refused_before_signing():
    agent = Agent.generate()
    pays = [{"pubkey": "02" + "aa" * 32, "value": 1}]
    with pytest.raises(ValueError):
        agent.sign_spend("abcd", pays)
    with pytest.raises(ValueError):
        agent.sign_spend("zz" * 32, pays)
    # A spend that pays nobody is the shape of a client that built its
    # inputs before its outputs -- the mistake the old order invited.
    with pytest.raises(ValueError):
        agent.sign_spend("ab" * 32, [])
