"""Cross-language conformance for the *other* signature an agent makes:
a spend of one of its own outputs, which is what each input of
``POST /wallet/send`` carries. Verified against
``tests/fixtures/output_fixtures.json``, generated by the same Rust
program as the envelope fixtures (``sdk/examples/gen_fixtures.rs``)
from ``btclib::crypto::Signature::sign_output`` -- the exact code the
hub and the node verify against.

Regenerate the fixture file with: cargo run -p sdk --example gen_fixtures
"""

import json
from pathlib import Path

import pytest

from itx_agent_sdk.envelope import Agent

FIXTURES_PATH = Path(__file__).parent / "fixtures" / "output_fixtures.json"

with open(FIXTURES_PATH, encoding="utf-8") as f:
    FIXTURES = json.load(f)


def test_fixture_file_is_present_and_non_empty():
    assert len(FIXTURES) >= 3


@pytest.mark.parametrize("fixture", FIXTURES, ids=[f["name"] for f in FIXTURES])
def test_signing_an_output_hash_matches_the_chain_byte_for_byte(fixture):
    """The hash arrives exactly as the hub reports it (`hex::encode` of
    `Hash::as_bytes`) and the signature has to be the one
    `Signature::sign_output` makes: RFC6979, low-S, `r || s`."""
    agent = Agent.from_private_key_hex(fixture["private_key_hex"])
    assert agent.pubkey_hex == fixture["pubkey_hex"]
    assert agent.sign_output(fixture["hash"]) == fixture["expected_signature_hex"]


def test_the_same_output_signed_by_two_keys_is_two_signatures():
    by_name = {f["name"]: f for f in FIXTURES}
    a, b = by_name["small_output_key_a"], by_name["small_output_other_key"]
    assert a["value"] == b["value"] and a["unique_id"] == b["unique_id"]
    assert a["expected_signature_hex"] != b["expected_signature_hex"]


def test_an_output_signature_is_not_an_envelope_signature():
    """One SHA-256 round over the hash bytes, not two over a string: an
    implementation that reused `sign_message` on the hex would produce
    something that verifies nowhere."""
    fixture = FIXTURES[0]
    agent = Agent.from_private_key_hex(fixture["private_key_hex"])
    assert agent.sign_message(fixture["hash"]) != fixture["expected_signature_hex"]


def test_a_hash_that_is_not_32_bytes_is_refused_before_signing():
    agent = Agent.generate()
    with pytest.raises(ValueError):
        agent.sign_output("abcd")
    with pytest.raises(ValueError):
        agent.sign_output("zz" * 32)
